### ISSUE TITLE
Typo in `get_online_data`

### ISSUE THREAD

**Issue by mrlazy1708** [LithiumDA/L_inf-PINN#1]
Hi! It seems that `domain_bsz` in these two lines should be `boundary_size`. But since their values are identical in your experiment, it's not a big issue.
https://github.com/LithiumDA/L_inf-PINN/blob/b32ea598fb8a27f7c1241fbcd6697787ea8afef6/src/hjb/data.py#L20-L21

**Comment by LithiumDA** [comment]
This is a good catch. I have just fixed it. Thanks for letting me know!
